#!/usr/bin/env bash

# This script configures the container to run nginx as the nginx user

# Install nginx
apt-get update
apt-get install -y nginx

# Make sure nginx is not running as root
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Make sure nginx is listening on all active IPs on port 8080
sed -i "s/listen\s*80;/listen 8080;/" /etc/nginx/sites-available/default

# Restart nginx to apply changes
service nginx restart

