#!/usr/bin/env bash
# This script configures a server to listen on port 80 of all the server’s active IPv4 IPs using Nginx

# Install nginx if not already installed
if [ ! -x "$(command -v nginx)" ]; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Remove the default Nginx site config
sudo rm /etc/nginx/sites-enabled/default

# Create a new Nginx site config
sudo bash -c 'cat > /etc/nginx/sites-available/new-site << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Create a symbolic link from the new site config to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/new-site /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart

