#!/usr/bin/env bash
# Configures a server to listen on port 80

sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart

